### ISSUE TITLE
md5 format to md_5

### ISSUE THREAD

**Issue by rudo0149** [zahash/jsoncodegen#2]
```rust
// {"any_md5": "..."} -> 

use serde::{Serialize, Deserialize};
#[derive(Serialize, Deserialize, Debug)]
pub struct Root {
    #[serde(rename = "any_md5")]
    pub any_md_5: String,
}
```

Should it be a bug or a feature?

**Comment by zahash** [comment]
you mean the variable name should have been "any_md5" instead of "any_md_5"?

**Comment by rudo0149** [comment]
yeah, like md5, rc4, etc.

**Comment by zahash** [comment]
i tried to write my own case converter but it was too complicated and annoying and buggy. so i ended up using some other crate. and looks like it puts underscore between letters and numbers everytime.

but this only happens with snake case

maybe there is a way to change this behaviour but for now, i can't prioritize this because there are a few other more important bugs.

**Comment by rudo0149** [comment]
<https://transform.tools/json-to-rust-serde>

```rust
use serde_derive::Deserialize;
use serde_derive::Serialize;

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Root {
    #[serde(rename = "any_md5")]
    pub any_md5: String,
}

```
This website works fine with this case, maybe it add a way to identify camelCase, but it add rename for every field looks tooo bloated, I prefer the Rust version you converted.\
Anyway, thanks for your working. Recently I'm dealing with web develop in Rust and lots of response json need to be deserialized, your converter actually help me save more time \:)
